# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 07:49
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=20)),
                ('description', markdownx.models.MarkdownxField()),
                ('due', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('dissemination', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeliverablePartnerPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Deliverable')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=20)),
                ('description', markdownx.models.MarkdownxField()),
                ('due', models.PositiveIntegerField()),
                ('verification', markdownx.models.MarkdownxField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MilestonePartnerPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.DecimalField(decimal_places=2, max_digits=6)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('partnername', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=80)),
                ('description', markdownx.models.MarkdownxField()),
                ('country', models.CharField(max_length=3)),
                ('PMcost', models.FloatField()),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=20)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('description', markdownx.models.MarkdownxField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskPartnerPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.DecimalField(decimal_places=2, max_digits=6)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Workpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=20)),
                ('objectives', markdownx.models.MarkdownxField()),
                ('description', markdownx.models.MarkdownxField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='wp',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Workpackage'),
        ),
        migrations.AddField(
            model_name='milestonepartnerpm',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='maintask',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.Task'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='secondarytasks',
            field=models.ManyToManyField(related_name='secondaryTasks', to='proposal.Task'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='wp',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Workpackage'),
        ),
        migrations.AddField(
            model_name='deliverablepartnerpm',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='maintask',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.Task'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='secondarytasks',
            field=models.ManyToManyField(related_name='secondarytasks', to='proposal.Task'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='wp',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Workpackage'),
        ),
    ]
