# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20170302_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisseminationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10)),
                ('long', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProducableTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10)),
                ('long', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='dissemination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.DisseminationTypes'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.ProducableTypes'),
        ),
    ]
