# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20170302_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliverablePartnerPM',
            new_name='DeliverablePartnerTaskPM',
        ),
        migrations.RenameModel(
            old_name='MilestonePartnerPM',
            new_name='MilestonePartnerTaskPM',
        ),
    ]
