# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0013_auto_20170308_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('name', models.CharField(help_text='This name is used to refer to the textblock in templates', max_length=64, verbose_name='Short name of the textblock')),
                ('description', models.TextField(help_text='Provide a brief description of this block;leave empty if clear; does not end up in output', verbose_name='Brief description')),
                ('filename', models.CharField(blank=True, help_text='Provide a filename if you want the content of this textblock to written to a markdown file. If empty, no file is produced automatically; content has to be used in a template explicitly, then.', max_length=64, null=True, verbose_name='Filename for the content of the textblock')),
                ('textblock', markdownx.models.MarkdownxField(help_text='Actual text for this block, in Markdown format', verbose_name='Actual text')),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
    ]
