# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0015_auto_20170308_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='callobjectives',
            field=models.CharField(blank=True, help_text='Use identifiers or short names from call', max_length=128, null=True, verbose_name='Call objectives'),
        ),
    ]
