# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0022_task_objectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('type', models.CharField(help_text='Short form of partner types', max_length=20)),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='infrastructure',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Significant infrastructure and/or major technical equipment, relevant to the project', verbose_name='Significant infrastructure'),
        ),
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='proposal.Partnertype'),
            preserve_default=False,
        ),
    ]
