# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0024_partnertype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='type',
            new_name='partnertype',
        ),
        migrations.RenameField(
            model_name='partnertype',
            old_name='type',
            new_name='shortname',
        ),
    ]
