version: '3'
services:
        propgen-db:
                build: ./mysql
                ports:
                        - "33306:3306"
                env_file:
                        - ./mysql/conf/env 
        propgen-be:
                build: ./django/
                command: [bash, "-c", "./post_build_setup.sh && uwsgi --socket :8000 --module django_propgen.wsgi"]
                volumes:
                        - ./django/static/:/code/static
                        - ./django/media/:/code/media
                        #- ./django/:/code
                        #- ./django/conf/:/etc/nginx/sites-enabled/
                depends_on:
                        - propgen-db
        propgen-lb:
                image: nginx
                ports:
                        - "80:8091"
                volumes:
                        - ./nginx/conf/my_vhost.conf:/etc/nginx/conf.d/django_propgen.conf
                        - ./nginx/conf/uwsgi_params:/etc/nginx/uwsgi_params
                        - ./django/static/:/var/static/
                        - ./django/media/:/var/media/
                command: [nginx, '-g', 'daemon off;']
                depends_on:
                        - propgen-be
        propgen-fe:
                build: ./ng-propgen
                ports: 
                       - "48484:80"

