# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Descriptive title')),
                ('included', models.BooleanField(verbose_name='Include this block in ouput')),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
    ]
