# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20170302_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Determine processing order in output')),
                ('title', models.CharField(max_length=512, verbose_name='Project title')),
                ('shortname', models.CharField(max_length=128, verbose_name='Project short name or acronym')),
                ('duration', models.PositiveIntegerField(verbose_name='Project duration (in months)')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner', verbose_name='Project coordinator')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
