# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_auto_20170302_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverablepartnertaskpm',
            options={'verbose_name': 'PM per partner, per task, per deliverable'},
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='secondarytasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondarytasks', to='proposal.Task'),
        ),
    ]
