# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0014_textblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='callid',
            field=models.CharField(blank=True, help_text='EU call ID like ICT FP7-ICT-2012-8 ', max_length=30, null=True, verbose_name='Call identifier'),
        ),
        migrations.AddField(
            model_name='project',
            name='coordinatorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email of the coordinating person'),
        ),
        migrations.AddField(
            model_name='project',
            name='coordinatorName',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name of coordinating person'),
        ),
        migrations.AddField(
            model_name='project',
            name='coordinatorPhone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone/FAX number of coordinator'),
        ),
        migrations.AddField(
            model_name='project',
            name='projecttype',
            field=models.CharField(blank=True, help_text='Project type like STREP, IA, IP, ...', max_length=64, null=True, verbose_name='Project type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.Partner', verbose_name='Project coordinator (partner)'),
        ),
    ]
