# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 10:57
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0017_auto_20170309_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='individuals',
            field=markdownx.models.MarkdownxField(blank=True, help_text='CV or description of key personnel', verbose_name='Individual researchers'),
        ),
        migrations.AddField(
            model_name='partner',
            name='infrastructure',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Siginificant infrastructure and/or major technical equipment, relevant to the project', verbose_name='Significant infrastructure'),
        ),
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=markdownx.models.MarkdownxField(blank=True, help_text='a description of the legal entity and its main tasks, with an explanation of how its profile matches the tasks in the proposal', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partnerprojects',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Up to 5 previous project or activities, relevant to the proposal', verbose_name='Previous projects'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partnerpublications',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Up to 5 relevant publications, products, services', verbose_name='Relevant publications, products and/or services'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='General description text, will appear before the subsections defined below. Typically empty if you fill in the following sections.', verbose_name='Partner description in general'),
        ),
    ]
