# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0019_auto_20170313_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='verification',
            field=models.TextField(),
        ),
    ]
