# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0020_auto_20170314_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='secondarytasks',
            field=models.ManyToManyField(blank=True, related_name='deliverable_secondaryTasks', to='proposal.Task'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='secondarytasks',
            field=models.ManyToManyField(related_name='milestone_secondaryTasks', to='proposal.Task'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='verification',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
