# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:29
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0021_auto_20170315_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='objectives',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
